[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[redirects]]
  from = "https://baskinemiliaromagna.netlify.app/*"
  to = "https://www.baskinemiliaromagna.it/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://www.baskinemiliaromagna.it/*"
  to = "https://www.baskinemiliaromagna.it/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://baskinemiliaromagna.it/*"
  to = "https://www.baskinemiliaromagna.it/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://baskinemiliaromagna.it/*"
  to = "https://www.baskinemiliaromagna.it/:splat"
  status = 301
  force = true
